### ISSUE TITLE
可以提供debian10.10和debian10.13的支持吗

### ISSUE THREAD

**Issue by x93008** [lcpu-club/loong-dockerfiles#2]
由于内陆linux系统发行版基本上都是UOS和麒麟，这两个系统有很长一段时间是基于debian10.10和debian10.13开发的，如果能支持这个版本的龙芯docker，研发做软件适配会方便很多。

**Comment by wszqkzqk** [comment]
可能较难，这两个版本并没有适合的龙芯新世界移植。

**Comment by leavelet** [comment]
debian 10.10 和 debian 10.13 应该指的都是旧世界？那应该可以用[龙芯官方的旧世界仓库](https://cr.loongnix.cn)
